alt-require: true
attr-lowercase: true
attr-no-duplication: true
attr-unsafe-chars: true
attr-value-double-quotes: true
attr-value-not-empty: false
doctype-first: true
doctype-html5: true
head-script-disabled: true
href-abs-or-rel: false
id-class-ad-disabled: true
id-class-value: dash
id-unique: true
inline-script-disabled: false
inline-style-disabled: true
space-tab-mixed-disabled: space
spec-char-escape: true
src-not-empty: true
style-disabled: true
tag-pair: true
tag-self-close: false
tagname-lowercase: true
title-require: true
printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
trailingComma: all
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: avoid
proseWrap: always
rules:
  block-no-empty: true
  color-no-invalid-hex: true
  font-family-no-duplicate-names: true
  font-family-no-missing-generic-family-keyword: true
  function-calc-no-invalid: true
  function-calc-no-unspaced-operator: true
  function-linear-gradient-no-nonstandard-direction: true
  string-no-newline: true
  unit-no-unknown: true
  property-no-unknown: true
  declaration-block-no-duplicate-properties: true
  comment-empty-line-before:
    - always
    - ignore:
        - stylelint-commands
        - after-comment
  declaration-colon-space-after: always
  declaration-no-important: true
  indentation:
    - 2
    - ignore:
        - inside-parens
  max-empty-lines: 2
  rule-empty-line-before:
    - always
    - except:
        - first-nested
      ignore:
        - after-comment
